server:
  port: 8081
  servlet:
    context-path: /book-management-provider

spring:
  web:
    resources:
      static-locations: 
        - /public/
        - classpath:/public/
        - /static/
        - classpath:/static/
  application:
    name: dubbo-book-management-provider
    #配置数据源信息
  datasource:
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #设置字符集
    url: jdbc:mysql://127.0.0.1:3306/schema_test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: password


mybatis:
  type-aliases-package: com.paul.book.management.api.entity
  mapper-locations: com/paul/book/management/provider/mapper/*.xml
  configuration:
    cache-enabled: true

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
    username: admin
    password: password
    timeout: 2000
  protocol:
    name: dubbo
    port: 20890
  provider:
    token: true
  # 扫描 @DubboService 注解
  scan:
    base-packages: com.paul.book.management.provider.service.impl
  
